# modified from usethis::use_github_action_check_standard()
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7 1 */3 *"
  workflow_dispatch:
name: R-CMD-check
jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest}
          - {os: ubuntu-latest}
          - {os: windows-latest}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: any::rcmdcheck
      - uses: r-lib/actions/check-r-package@v2
      - name: Test results
        if: always()
        run: cat check/faviconPlease.Rcheck/tests/tinytest.Rout*
        shell: bash {0}
