# modified from usethis::use_github_action_check_standard()
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7 1 * *"
  workflow_dispatch:
name: R-CMD-check
jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest}
          - {os: macos-latest}
          - {os: ubuntu-22.04, rspm: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"}
    env:
      _R_CHECK_CRAN_INCOMING_REMOTE_: false
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_COMPILE_AND_INSTALL_PACKAGES: never
      RSPM: ${{ matrix.config.rspm }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
      # Need to update APT manually since I am using pre-installed R
      - name: Update APT
        if: runner.os == 'Linux'
        run: sudo apt-get update
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2-branch
        with:
          cache-version: 1
          extra-packages: any::rcmdcheck
      - name: Session information
        run: sessionInfo()
        shell: Rscript {0}
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
